#
# Author:: Thijs Houtenbos <thoutenbos@schubergphilis.com>
# Cookbook:: acme
#
# Copyright 2015-2016 Schuberg Philis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
    - ["private_network", {ip: "33.33.33.200"}]

platforms:
- name: centos-7
  driver:
    box: centos/7 # virtualbox
    image: centos-7-0-x64   # digitalocean
- name: ubuntu-14.04
  run_list:
    - recipe[apt]
  driver:
    box: bento/ubuntu-14.04
    image: ubuntu-14-04-x64
  attributes:
    nginx:
      install_method: source

provisioner:
  name: chef_zero
  log_level: info

suites:
- name: http
  run_list:
  - recipe[acme_server]
  - recipe[acme_client::http]
  attributes:
    boulder:
      revision: 2d33a9900cafe82993744fe73bd341fe47df2171
    acme:
      endpoint: http://127.0.0.1:4000
      contact:
      - mailto:admin@example.com

- name: ssl
  run_list:
  - recipe[acme_server]
  - recipe[acme_client::ssl]
  attributes:
    boulder:
      revision: 2d33a9900cafe82993744fe73bd341fe47df2171
    acme:
      endpoint: http://127.0.0.1:4000
      contact:
      - mailto:admin@example.com
    nginx:
      server_names_hash_bucket_size: 256
